apiVersion: v1
kind: Namespace
metadata:
  name: c2c-metaage-aws-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c2c-metaage-aws-deployment
  namespace: c2c-metaage-aws-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 792373136340.dkr.ecr.us-east-2.amazonaws.com/cisco_pov:d87d0b8d0c89f3e2cb2af0333db72e44641feadc

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: c2c-metaage-aws-label
  name: c2c-metaage-aws-service
  namespace: c2c-metaage-aws-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---